Repository TobySuch/Shifter, pull requests merged in 2023-06, with the labels that each got.

#177 Frontend build pipeline
  .dockerignore
  .env EXAMPLE
  .github/dependabot.yml
  .github/workflows/main.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  docker/Dockerfile
  docker/dev/Dockerfile.dev
  docker/dev/Dockerfile.frontend.dev
  docker/dev/docker-compose.dev.yml
  docker/dev/docker-compose.test.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  requirements.txt
  shifter/assets/css/style.css
  shifter/assets/js/filepond.js
  shifter/assets/js/flowbite.js
  shifter/entrypoint.sh
  shifter/entrypoint_tailwind.sh
  shifter/package-lock.json
  shifter/package.json
  shifter/shifter/settings.py
  shifter/shifter_auth/templates/shifter_auth/login.html
  shifter/shifter_files/static/shifter_files/css/filepond.min.css
  shifter/shifter_files/static/shifter_files/js/filepond.min.js
  shifter/shifter_files/static/shifter_files/js/jszip.min.js
  shifter/shifter_files/templates/shifter_files/file_upload.html
  shifter/static/img/logo.svg
  shifter/tailwind.config.js
  shifter/templates/403.html
  shifter/templates/404.html
  shifter/templates/base.html
  shifter/theme/__init__.py
  shifter/theme/apps.py
  shifter/theme/context_processors.py
  shifter/theme/static_src/.gitignore
  shifter/theme/static_src/package-lock.json
  shifter/theme/static_src/package.json
  shifter/theme/static_src/postcss.config.js
  shifter/theme/static_src/src/styles.css
  shifter/theme/static_src/tailwind.config.js
  shifter/theme/tests.py
  shifter/webpack.config.js
Labels: documentation, enhancement, dependencies, frontend, config

#175 adding footer
  shifter/templates/base.html
Labels: enhancement, frontend

#179 #146: Build assets into image
  docker/Dockerfile
  docker/docker-compose.yml
  shifter/entrypoint.sh
Labels: enhancement, config
